import matplotlib.pyplot as plt
import pandas as pd
import os

if not os.path.exists("graphs"):
    os.makedirs("graphs", exist_ok=True)

df_fraud_percent_unemployment = pd.read_csv("data/clean_fraud_percent_unemployment.csv")
df_fraud_percent_unemployment.set_index("Year",inplace=True)

years = range(2006,2026)
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(years,df_fraud_percent_unemployment["All Benefits Fraud"][years], label="Total Benefits Fraud (%)",color="black", linewidth=2)
ax.plot(years,df_fraud_percent_unemployment["Universal Credit Fraud"][years], label="Universal Credit Fraud (%)",color="red")
ax.plot(years,df_fraud_percent_unemployment["State Pension Fraud"][years], label="State Pension Fraud (%)",color="darkorange")
ax.plot(years,df_fraud_percent_unemployment["Personal Independence Payment Fraud"][years], label="Personal Independence Payment (%)",color="orange")
ax.plot(years,df_fraud_percent_unemployment["Housing Benefit Total Fraud"][years], label="Housing Benefit Fraud (%)",color="gold")
ax.plot(years,df_fraud_percent_unemployment["Pension Credit Fraud"][years], label="Pension Credit Fraud (%)",color="lime")
ax.plot(years,df_fraud_percent_unemployment["Carer\'s Allowance Fraud"][years], label="Carer's Allowance Fraud (%)",color="olivedrab")
ax.plot(years,df_fraud_percent_unemployment["Employment and Support Allowance Fraud"][years], label="Employment and Support Allowance Fraud (%)",color="green")
ax.plot(years,df_fraud_percent_unemployment["Attendance Allowance Fraud"][years], label="Attendance Allowance Fraud (%)",color="teal")
ax.plot(years,df_fraud_percent_unemployment["Disability Living Allowance Fraud"][years], label="Disability Living Allowance Fraud (%)",color="blue")
ax.plot(years,df_fraud_percent_unemployment["Jobseeker\'s Allowance Fraud"][years], label="Jobseeker's Allowance Fraud (%)",color="darkslateblue")
ax.plot(years,df_fraud_percent_unemployment["Income Support Total Fraud"][years], label="Income Support Total Fraud (%)",color="indigo")
ax.plot(years,df_fraud_percent_unemployment["Incapacity Benefit Fraud"][years], label="Incapacity Benefit Fraud(%)",color="violet")
ax.plot(years,df_fraud_percent_unemployment["Interdependencies Fraud"][years], label="Interdependencies Fraud (%)",color="fuchsia")
ax.axvline(2019, linestyle="dashed", color="darkred", label="Methodology Change")
ax.legend(loc='upper left')
ax.set_title("Benefits Fraud by Program Over Time (% of Expenditure)")
ax.set_xlabel("Year")
ax.set_xticks(range(2006,2026,2))
ax.set_ybound(0,14)
_ = ax.set_yticks(range(1,14))
plt.savefig('graphs/all_programs.png')

df_fraud_dollars_unemployment = pd.read_csv("data/clean_fraud_dollars_unemployment.csv")
df_fraud_dollars_unemployment.set_index("Year",inplace=True)

fig, ax = plt.subplots(figsize=(10, 10),nrows=2)
ax[0].plot(years,df_fraud_dollars_unemployment["All Benefits Fraud"][years]/1e9, label="Total Benefits Fraud ($Billions)",color="royalblue")
ax[0].plot(years,df_fraud_dollars_unemployment["16+ Unemployment Rate"][years], label="16+ Unemployment Rate (%)",color="indigo")
ax[0].axvline(2019, linestyle="dashed", color="darkred", label="Methodology Change")
ax[0].legend()
ax[0].set_title("Benefits Fraud ($) vs 16+ Unemployment Rate (%)")
ax[0].set_xlabel("Year")
ax[0].set_xticks(range(2006,2026,2))
ax[0].set_ybound(0,9)
ax[0].set_yticks(range(1,9))
ax[1].plot(years,df_fraud_percent_unemployment["All Benefits Fraud"][years], label="Total Benefits Fraud (% of Expenditures)",color="royalblue")
ax[1].plot(years,df_fraud_percent_unemployment["16+ Unemployment Rate"][years], label="16+ Unemployment Rate (%)",color="indigo")
ax[1].axvline(2019, linestyle="dashed", color="darkred", label="Methodology Change")
ax[1].legend()
ax[1].set_title("Benefits Fraud (%) vs 16+ Unemployment Rate (%)")
ax[1].set_xlabel("Year")
ax[1].set_xticks(range(2006,2026,2))
ax[1].set_ybound(0,9)
_ = ax[1].set_yticks(range(1,9))
plt.savefig('graphs/total_fraud.png')

df_fraud_percent_no_uc_unemployment = pd.read_csv("data/clean_fraud_percent_no_uc_unemployment.csv")
df_fraud_percent_no_uc_unemployment.set_index("Year",inplace=True)

fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(years,df_fraud_percent_no_uc_unemployment["Benefits Fraud"][years], label="Benefits Fraud Excluding Universal Credit (%)",color="royalblue", linewidth=2)
ax.plot(years,df_fraud_dollars_unemployment["16+ Unemployment Rate"][years], label="16+ Unemployment Rate (%)",color="indigo")
ax.axvline(2019, linestyle="dashed", color="darkred", label="Methodology Change")
ax.legend(loc='upper left')
ax.set_title("Benefits Fraud by Program Over Time Excluding Universal Credit (% of Expenditure)")
ax.set_xlabel("Year")
ax.set_xticks(range(2006,2026,2))
ax.set_ybound(0,14)
_ = ax.set_yticks(range(1,14))
plt.savefig('graphs/no_uc.png')
